[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.18"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bull_bear_program = "FKkP7JrUxzVYgZfgvb1J86SNuFmPAEtCURD6snMtcjPu"

[programs.devnet]
bull_bear_program = "FKkP7JrUxzVYgZfgvb1J86SNuFmPAEtCURD6snMtcjPu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
validator = """solana-test-validator --reset \
    --bpf-program FsJ3A3u2vn5cTVofAjvy6y5kwABJAqYWpe4975bi2epH tests/clones/pythOracle.so \
    --bpf-program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA tests/clones/tokenProgram.so \
    --clone 7UVimffxr9ow1uXYxsr4LHAcV58mLzhmwaeKvJ1pjLiE \
    --clone 6B23K3tkb51vLZA14jcEQVCA1pfHptzEHFA93V5dYwbT \
    --clone 42amVS4KgzR9rA28tkVYqVXjq9Qa8dcZQMbH5EYFX6XC \
    --clone 3T3R5KTAXgMF5KVw6v38qUfSUernCHQwYFzfVo1jdjMX --url 'https://api.mainnet-beta.solana.com'"""
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/bull-bear-program.ts"
init = "yarn ts-node scripts/initializeProtocol.ts"
start_round = "yarn ts-node scripts/startRound.ts"
test_price_feed = "yarn ts-node scripts/testPriceFeed.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.genesis]]
address = "FsJ3A3u2vn5cTVofAjvy6y5kwABJAqYWpe4975bi2epH"
program = "tests/clones/pythOracle.so"

[[test.genesis]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
program = "tests/clones/tokenProgram.so"

[[test.validator.clone]]
address = "7UVimffxr9ow1uXYxsr4LHAcV58mLzhmwaeKvJ1pjLiE"

[[test.validator.clone]]
address = "6B23K3tkb51vLZA14jcEQVCA1pfHptzEHFA93V5dYwbT"

[[test.validator.clone]]
address = "42amVS4KgzR9rA28tkVYqVXjq9Qa8dcZQMbH5EYFX6XC"

[[test.validator.clone]]
address = "3T3R5KTAXgMF5KVw6v38qUfSUernCHQwYFzfVo1jdjMX"