[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.18"

[features]
resolution = true
skip-lint = false

[programs.devnet]
bull_bear_program = "FKkP7JrUxzVYgZfgvb1J86SNuFmPAEtCURD6snMtcjPu"

[programs.localnet]
bull_bear_program = "FKkP7JrUxzVYgZfgvb1J86SNuFmPAEtCURD6snMtcjPu"
mock_pyth_pull = "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ"
mock_pyth_push = "3L2Sboo2rcRmatUJLr1eu3ZqtwYu3XXKv77qBnZnRRmW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/start_round.ts"
init = "yarn ts-node scripts/initializeProtocol.ts"
create = "yarn ts-node scripts/initializeGame.ts"
start = "yarn ts-node scripts/startGame.ts"
start_round = "yarn ts-node scripts/startRound.ts"
test_price_feed = "yarn ts-node scripts/testPriceFeed.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

# this should be uncommented if tested with solana test validator validator run with `./setup_validator.sh`
# [workspace]
# exclude = [
#     "programs/mock_pyth_push",
#     "programs/mock_pyth_pull"
# ]



